load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kvfs",
    srcs = ["cas.go"],
    importpath = "github.com/iampat/cloudy-neigh/kvfs",
    visibility = ["//visibility:public"],
    deps = ["//objectstore"],
)

go_test(
    name = "kvfs_test",
    srcs = [
        "cas_internal_test.go",
        "cas_test.go",
    ],
    embed = [":kvfs"],
    deps = [
        "//objectstore",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
