load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kvfs",
    srcs = [
        "branch.go",
        "cas.go",
        "manifest.go",
    ],
    importpath = "github.com/iampat/cloudy-neigh/kvfs",
    visibility = ["//visibility:public"],
    deps = [
        "//objectstore",
        "//proto/kvfs/v1:kvfs",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "kvfs_test",
    srcs = [
        "branch_test.go",
        "cas_internal_test.go",
        "cas_test.go",
        "manifest_test.go",
    ],
    embed = [":kvfs"],
    deps = [
        "//objectstore",
        "//proto/kvfs/v1:kvfs",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_protobuf//proto",
    ],
)
