load("@aspect_rules_lint//format:defs.bzl", "format_multirun")
load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@rules_go//go:def.bzl", "TOOLS_NOGO", "nogo")
load("@pip//:requirements.bzl", "all_whl_requirements")
load("@rules_python_gazelle_plugin//manifest:defs.bzl", "gazelle_python_manifest")
load("@rules_python_gazelle_plugin//modules_mapping:def.bzl", "modules_mapping")
load("@rules_uv//uv:pip.bzl", "pip_compile")

exports_files([
    "requirements.in",
    "requirements.txt",
])

pip_compile(
    name = "requirements",
    requirements_in = "//:requirements.in",
    requirements_txt = "//:requirements.txt",
)

modules_mapping(
    name = "modules_map",
    wheels = all_whl_requirements,
)

gazelle_python_manifest(
    name = "gazelle_python_manifest",
    modules_mapping = ":modules_map",
    pip_repository_name = "pip",
    requirements = "//:requirements.txt",
)

# gazelle:prefix github.com/iampat/cloudy-neigh
# gazelle:exclude .venv
# gazelle:exclude datasets
gazelle_binary(
    name = "gazelle_bin",
    languages = [
        "@bazel_gazelle//language/go",
        "@bazel_gazelle//language/proto",
        "@rules_python_gazelle_plugin//python",
    ],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

buildifier(
    name = "buildifier",
)

format_multirun(
    name = "format",
    go = "@aspect_rules_lint//format:gofumpt",
    python = "@aspect_rules_lint//format:ruff",
    visibility = ["//visibility:public"],
)

nogo(
    name = "nogo",
    config = "nogo_config.json",
    visibility = ["//visibility:public"],
    deps = TOOLS_NOGO,
)
