load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "cloudy_lib",
    srcs = ["main.go"],
    importpath = "github.com/iampat/cloudy-neigh/cmd/cloudy",
    visibility = ["//visibility:private"],
    deps = [
        "//grpcapi",
        "//ingest",
        "//logstream",
        "//objectstore",
        "//proto/cloudyneigh/v1:cloudyneigh",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_x_sync//errgroup",
    ],
)

go_binary(
    name = "cloudy",
    embed = [":cloudy_lib"],
    visibility = ["//visibility:public"],
)
