load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto_grpc_python//:defs.bzl", "python_grpc_library")

proto_library(
    name = "cloudyneighpb_proto",
    srcs = ["index.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "cloudyneighpb_go_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_proto",
        "@io_bazel_rules_go//proto:go_grpc_v2",
    ],
    importpath = "github.com/iampat/cloudy-neigh/proto/cloudyneigh/v1",
    proto = ":cloudyneighpb_proto",
    visibility = ["//visibility:public"],
)

python_grpc_library(
    name = "cloudyneighpb_py_grpc",
    protos = [":cloudyneighpb_proto"],
    visibility = ["//visibility:public"],
)
