syntax = "proto3";

package cloudyneigh.v1;

option go_package = "github.com/iampat/cloudy-neigh/proto/cloudyneigh/v1;cloudyneighpb";

message Vector {
  repeated float values = 1;
}

message AttributeValue {
  oneof value {
    string string_value = 1;
    // int64 int_value = 2;
    // double float_value = 3;
    // bool bool_value = 4;
    // bytes bytes_value = 5;
  }
}

message Record {
  string id = 1;
  map<string, Vector> vectors = 2;
  map<string, AttributeValue> attributes = 3;
}

message UpsertRequest {
  string namespace = 1;
  repeated Record records = 2;
}

message UpsertResponse {
  uint32 upserted_count = 1;
}

message DeleteRequest {
  string namespace = 1;
  repeated string ids = 2;
}

message DeleteResponse {
  uint32 deleted_count = 1;
}

message EqualityFilter {
  string field = 1;
  AttributeValue value = 2;
}

message QueryRequest {
  string namespace = 1;
  repeated float vector = 2;
  uint32 top_k = 3;
  EqualityFilter filter = 4;
  string vector_column = 5;
}

message ScoredRecord {
  Record record = 1;
  float score = 2;
}

message QueryResponse {
  repeated ScoredRecord hits = 1;
}

service IngestService {
  rpc Upsert(UpsertRequest) returns (UpsertResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}

service QueryService {
  rpc Query(QueryRequest) returns (QueryResponse);
}
