load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "server",
    srcs = [
        "server.go",
        "validate.go",
    ],
    importpath = "github.com/iampat/cloudy-neigh/server",
    visibility = ["//visibility:public"],
    deps = [
        "//index",
        "//proto/cloudyneigh",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "server_test",
    srcs = ["server_test.go"],
    deps = [
        ":server",
        "//cas",
        "//index",
        "//proto/cloudyneigh",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//status",
        "@org_golang_google_grpc//test/bufconn",
        "@org_golang_google_protobuf//proto",
    ],
)
