load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "xtime",
    srcs = ["sleep.go"],
    importpath = "github.com/iampat/cloudy-neigh/internal/xtime",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "xtime_test",
    srcs = ["sleep_test.go"],
    deps = [
        ":xtime",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
