load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cas",
    srcs = [
        "cas.go",
        "disk.go",
        "memory.go",
    ],
    importpath = "github.com/iampat/cloudy-neigh/internal/cas",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "cas_test",
    srcs = ["cas_test.go"],
    deps = [":cas"],
)
