load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "manifest",
    srcs = ["manifest.go"],
    importpath = "github.com/iampat/cloudy-neigh/manifest",
    visibility = ["//visibility:public"],
    deps = [
        "//objectstore",
        "//proto/storage/v1:storage",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_test(
    name = "manifest_test",
    srcs = ["manifest_test.go"],
    deps = [
        ":manifest",
        "//objectstore",
        "//proto/storage/v1:storage",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_protobuf//proto",
    ],
)
