load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "objectstore",
    srcs = [
        "driver.go",
        "gcs.go",
        "local.go",
        "mem.go",
        "objectstore.go",
        "open.go",
    ],
    importpath = "github.com/iampat/cloudy-neigh/objectstore",
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_cloud_go_storage//:storage",
        "@org_golang_google_api//googleapi",
        "@org_golang_google_api//iterator",
    ],
)

go_test(
    name = "objectstore_test",
    srcs = [
        "benchmark_test.go",
        "disk_test.go",
        "gcs_test.go",
        "open_test.go",
        "store_test.go",
    ],
    deps = [
        ":objectstore",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
