name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        go: [ go1.26 ]
        experimental: [ false ]
        include:
          - go: go1.27
            experimental: true
    steps:
    - uses: actions/checkout@v7
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}-${{ matrix.go }}
        repository-cache: true

    - name: Build
      run: bazel build --config=${{ matrix.go }} //...

    - name: Test (race)
      run: bazel test --config=${{ matrix.go }} --config=race //...

    - name: Benchmark
      run: bazel test --config=${{ matrix.go }} --test_output=all --test_arg=-test.v --test_arg=-test.bench=. --test_arg=-test.cpu=1 //...
